name: Tribes Production CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Typecheck
        run: npm run typecheck

      - name: Run Unit Tests
        run: npm run test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_KEY }}

      - name: Execute Deploy Script
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_USER: ${{ secrets.PROD_USER }}
        run: |
          # Overwrite deploy host parameters from GitHub secrets
          sed -i "s/REMOTE_HOST=.*/REMOTE_HOST=\"$PROD_USER@$PROD_HOST\"/" ./scripts/deploy.sh
          ./scripts/deploy.sh
